{{- if and .Values.argocd.enabled .Values.argocd.apiToken (not .Values.argocd.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-assistant.argocd.fullname" . }}
  labels:
    {{- include "platform-assistant.argocd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.argocd.existingSecretKey }}: {{ .Values.argocd.apiToken | quote }}
{{- end }}
